database_config: database.ini
activity_table: portal_activity
email_config_file: email_config.yaml
report_output_dir: output
config_dir: /configs/
time_zone_difference: 7

views_json_url: https://data.sfgov.org/api/search/views.json


activity:
  create:
    time_interval:  60 minutes
    report_fn: created_datasets
    database_table: created_datasets
    dt_format: \%Y-%m-%d %H:%M:%S
    timestamp_report_notification_col: first_seen
    report_cols: time, datasetid, name, first_seen, pub_dept, pub_freq, created_at
    email_msg:
      subject_line: TEST-CREATE PORTAL ACTIVITY LOG 
      subject_line_action: datasets have been created
      msg_header: <h3>Test - The following datasets have been created:</h3>
  delete:
    time_interval:  60 minutes
    report_fn: deleted_datasets
    database_table: deleted_datasets
    dt_format: \%Y-%m-%d %H:%M:%S
    report_cols: time, datasetid, name, last_seen, pub_dept, pub_freq, updated_at, created_at
    timestamp_report_notification_col: last_seen
    email_msg:
      subject_line: TEST-DELETE PORTAL ACTIVITY LOG 
      subject_line_action: datasets have been deleted
      msg_header: <h3>Test - The following datasets have been deleted:</h3>
  update:
    time_interval:  60 minutes
    report_fn: stale_and_delayed_datasets
    database_table: late_updated_datasets
    dt_format: \%Y-%m-%d %H:%M:%S
    timestamp_report_notification_col: last_checked
    report_cols: time, datasetid, name, last_checked, pub_health, updated_at, pub_dept, pub_freq, created_at
    email_msg:
      subject_line: TEST- STALE and DELAYED DATASETS PORTAL ACTIVITY LOG 
      subject_line_action: datasets have a publishing health of stale or deleted
      msg_header: <h3>Test - The following datasets have a publishing health of stale or deleted:</h3>
  stale_delayed_digest: 
    time_interval:  12 hours
    report_fn: stale_and_delayed_datasets
    database_table: late_updated_datasets
    dt_format: \%Y-%m-%d %H:%M:%S
    timestamp_report_notification_col: late_as_of
    report_cols: time, datasetid, name, pub_health, pub_dept, updated_at, pub_freq, days_last_updt, created_at, late_as_of
    email_msg:
      subject_line: TEST- STALE and DELAYED DATASETS PORTAL ACTIVITY DIGEST
      subject_line_action: datasets have a publishing health of stale or deleted
      msg_header: <h3>Test - The following datasets have a publishing health of stale or deleted:</h3>

email_msg_template:
  header:  <html> <head> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"></head><body><container>
  footer: </container></body></html>
